name: Build and Publish Docs
on:
  # Trigger the workflow on push only for the master branch
  push:
    branches:  
      - docs-ci-bug
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build documentation  
      run: |
        cd docs
        make html
        echo  "going to ls >"
        ls /home/runner/work/cloudflow/cloudflow/docs/../docs/target/staging
        echo  "docs >"
        ls /home/runner/work/cloudflow/cloudflow/docs/../docs/target/staging/docs
