on: push
name: Build and Test
jobs:
  build-and-test-scala:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build-and-test
      uses: agemooij/github-actions-sbt@master
      env:
        BINTRAY_PASSWORD: ${{ secrets.BINTRAY_PASSWORD }}
        BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
        SBT_OPTS: -Xms512M -Xmx2048M -Xss2M -XX:MaxMetaspaceSize=1024M
      with:
        entrypoint: scripts/build-all.sh
        args: test

  build-and-test-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build
      run: |
        set -e
        cd kubectl-cloudflow
        make test
